name: WDLCompanionWorldGuardSupport
main: wdl.worldguard.WorldGuardSupportPlugin
version: 0.0.1
author: Pokechu22
depend: [WDLCompanion, WorldGuard, WorldEdit]
website: http://dev.bukkit.org/bukkit-plugins/wdl-companion-worldguard-support/
description: Adds a ChunkOverride type, 'Owned WorldGuard regions', which allows a player to download in WorldGuard regions they own.